[linux_production]
srv-1 ansible_host=100.65.2.207 ansible_user=cyberrange
srv-2 ansible_host=100.65.4.161 ansible_user=cyberrange
srv-3 ansible_host=100.65.3.196 ansible_user=cyberrange

[all:vars]
# Use Python 3 on the remote hosts
ansible_python_interpreter=/usr/bin/python3

# Most of the mass deploy actions require privilege escalation
ansible_become=True
ansible_become_method=sudo

# Authentication:
# - Recommended: use SSH keys, or
# - Use --ask-pass / --ask-become-pass when running ansible-playbook, or
# - Store ansible_password in an Ansible Vault file instead of plaintext

